### ISSUE TITLE
Unknown chk parameter in uploadGJAccComment20

### ISSUE THREAD

**Issue by xparadoxical** [Wyliemaster/gddocs#20]
https://github.com/Wyliemaster/gddocs/blob/1e9c45e7170ab0af9722278b97dd97bec3631dc5/docs/endpoints/comments/uploadGJAccComment20.md#L27

**Comment by xBZZZZ** [comment]
see https://github.com/Wyliemaster/gddocs/issues/21#issuecomment-1836549748

**Comment by Wyliemaster** [comment]
Closing as its a duplicate
